name: Deploy to Fly

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "latest"

      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--classmap-authoritative"

      - run: ./vendor/bin/pest --ci -p

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - id: get-machine
        run: echo "::set-output name=id::$(flyctl machine list --json |  jq '.[] | select(.state == "started").id' )"

      - run: flyctl machine update ${{ steps.get-machine.outputs.id }} .

#      - run: curl --fail-with-body ${{ secrets.APP_URL }}/setup.php
      - run: curl -sS ${{ secrets.APP_URL }}/setup.php
